/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see robot.dSL.DSLPackage
 * @generated
 */
public interface DSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DSLFactory eINSTANCE = robot.dSL.impl.DSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Robot Behavior</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Robot Behavior</em>'.
   * @generated
   */
  RobotBehavior createRobotBehavior();

  /**
   * Returns a new object of class '<em>Behaviors</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Behaviors</em>'.
   * @generated
   */
  Behaviors createBehaviors();

  /**
   * Returns a new object of class '<em>Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression</em>'.
   * @generated
   */
  Expression createExpression();

  /**
   * Returns a new object of class '<em>Actions</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Actions</em>'.
   * @generated
   */
  Actions createActions();

  /**
   * Returns a new object of class '<em>Left Movement Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Left Movement Action</em>'.
   * @generated
   */
  LeftMovementAction createLeftMovementAction();

  /**
   * Returns a new object of class '<em>Right Movement Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Right Movement Action</em>'.
   * @generated
   */
  RightMovementAction createRightMovementAction();

  /**
   * Returns a new object of class '<em>Rotate Movement Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rotate Movement Action</em>'.
   * @generated
   */
  RotateMovementAction createRotateMovementAction();

  /**
   * Returns a new object of class '<em>Movement Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Movement Action</em>'.
   * @generated
   */
  MovementAction createMovementAction();

  /**
   * Returns a new object of class '<em>Expression Bracket</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Expression Bracket</em>'.
   * @generated
   */
  ExpressionBracket createExpressionBracket();

  /**
   * Returns a new object of class '<em>Touch Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Touch Literal</em>'.
   * @generated
   */
  TouchLiteral createTouchLiteral();

  /**
   * Returns a new object of class '<em>Color Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Color Literal</em>'.
   * @generated
   */
  ColorLiteral createColorLiteral();

  /**
   * Returns a new object of class '<em>Distance Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Distance Literal</em>'.
   * @generated
   */
  DistanceLiteral createDistanceLiteral();

  /**
   * Returns a new object of class '<em>AN Dexpression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>AN Dexpression</em>'.
   * @generated
   */
  ANDexpression createANDexpression();

  /**
   * Returns a new object of class '<em>ORexpression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ORexpression</em>'.
   * @generated
   */
  ORexpression createORexpression();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DSLPackage getDSLPackage();

} //DSLFactory
