/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see robot.dSL.DSLFactory
 * @model kind="package"
 * @generated
 */
public interface DSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.DSL.robot";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DSLPackage eINSTANCE = robot.dSL.impl.DSLPackageImpl.init();

  /**
   * The meta object id for the '{@link robot.dSL.impl.RobotBehaviorImpl <em>Robot Behavior</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.RobotBehaviorImpl
   * @see robot.dSL.impl.DSLPackageImpl#getRobotBehavior()
   * @generated
   */
  int ROBOT_BEHAVIOR = 0;

  /**
   * The feature id for the '<em><b>Behaviorlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_BEHAVIOR__BEHAVIORLIST = 0;

  /**
   * The number of structural features of the '<em>Robot Behavior</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_BEHAVIOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.BehaviorsImpl <em>Behaviors</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.BehaviorsImpl
   * @see robot.dSL.impl.DSLPackageImpl#getBehaviors()
   * @generated
   */
  int BEHAVIORS = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIORS__NAME = 0;

  /**
   * The feature id for the '<em><b>Sensor Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIORS__SENSOR_EXPRESSION = 1;

  /**
   * The feature id for the '<em><b>Actionlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIORS__ACTIONLIST = 2;

  /**
   * The number of structural features of the '<em>Behaviors</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BEHAVIORS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ExpressionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 2;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ActionsImpl <em>Actions</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ActionsImpl
   * @see robot.dSL.impl.DSLPackageImpl#getActions()
   * @generated
   */
  int ACTIONS = 3;

  /**
   * The number of structural features of the '<em>Actions</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link robot.dSL.impl.LeftMovementActionImpl <em>Left Movement Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.LeftMovementActionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getLeftMovementAction()
   * @generated
   */
  int LEFT_MOVEMENT_ACTION = 4;

  /**
   * The feature id for the '<em><b>Leftmove</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_MOVEMENT_ACTION__LEFTMOVE = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Left Movement Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEFT_MOVEMENT_ACTION_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.RightMovementActionImpl <em>Right Movement Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.RightMovementActionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getRightMovementAction()
   * @generated
   */
  int RIGHT_MOVEMENT_ACTION = 5;

  /**
   * The feature id for the '<em><b>Rightmove</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_MOVEMENT_ACTION__RIGHTMOVE = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Right Movement Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RIGHT_MOVEMENT_ACTION_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.RotateMovementActionImpl <em>Rotate Movement Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.RotateMovementActionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getRotateMovementAction()
   * @generated
   */
  int ROTATE_MOVEMENT_ACTION = 6;

  /**
   * The feature id for the '<em><b>Rotateleft</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_MOVEMENT_ACTION__ROTATELEFT = ACTIONS_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Leftdir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_MOVEMENT_ACTION__LEFTDIR = ACTIONS_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Rotateright</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_MOVEMENT_ACTION__ROTATERIGHT = ACTIONS_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Rightdir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_MOVEMENT_ACTION__RIGHTDIR = ACTIONS_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Rotate Movement Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROTATE_MOVEMENT_ACTION_FEATURE_COUNT = ACTIONS_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link robot.dSL.impl.MovementActionImpl <em>Movement Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.MovementActionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getMovementAction()
   * @generated
   */
  int MOVEMENT_ACTION = 7;

  /**
   * The feature id for the '<em><b>Actionenum</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVEMENT_ACTION__ACTIONENUM = 0;

  /**
   * The number of structural features of the '<em>Movement Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MOVEMENT_ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ExpressionBracketImpl <em>Expression Bracket</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ExpressionBracketImpl
   * @see robot.dSL.impl.DSLPackageImpl#getExpressionBracket()
   * @generated
   */
  int EXPRESSION_BRACKET = 8;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BRACKET__EXP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Expression Bracket</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_BRACKET_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.TouchLiteralImpl <em>Touch Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.TouchLiteralImpl
   * @see robot.dSL.impl.DSLPackageImpl#getTouchLiteral()
   * @generated
   */
  int TOUCH_LITERAL = 9;

  /**
   * The feature id for the '<em><b>Touch</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_LITERAL__TOUCH = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Touch Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOUCH_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ColorLiteralImpl <em>Color Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ColorLiteralImpl
   * @see robot.dSL.impl.DSLPackageImpl#getColorLiteral()
   * @generated
   */
  int COLOR_LITERAL = 10;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_LITERAL__COLOR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Color Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.DistanceLiteralImpl <em>Distance Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.DistanceLiteralImpl
   * @see robot.dSL.impl.DSLPackageImpl#getDistanceLiteral()
   * @generated
   */
  int DISTANCE_LITERAL = 11;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE_LITERAL__DISTANCE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Distance Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DISTANCE_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ANDexpressionImpl <em>AN Dexpression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ANDexpressionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getANDexpression()
   * @generated
   */
  int AN_DEXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AN_DEXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AN_DEXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>AN Dexpression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AN_DEXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link robot.dSL.impl.ORexpressionImpl <em>ORexpression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.impl.ORexpressionImpl
   * @see robot.dSL.impl.DSLPackageImpl#getORexpression()
   * @generated
   */
  int OREXPRESSION = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OREXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OREXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>ORexpression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OREXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link robot.dSL.RotateEnum <em>Rotate Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.RotateEnum
   * @see robot.dSL.impl.DSLPackageImpl#getRotateEnum()
   * @generated
   */
  int ROTATE_ENUM = 14;

  /**
   * The meta object id for the '{@link robot.dSL.ActionEnum <em>Action Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.ActionEnum
   * @see robot.dSL.impl.DSLPackageImpl#getActionEnum()
   * @generated
   */
  int ACTION_ENUM = 15;

  /**
   * The meta object id for the '{@link robot.dSL.TouchEnum <em>Touch Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.TouchEnum
   * @see robot.dSL.impl.DSLPackageImpl#getTouchEnum()
   * @generated
   */
  int TOUCH_ENUM = 16;

  /**
   * The meta object id for the '{@link robot.dSL.ColorEnum <em>Color Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see robot.dSL.ColorEnum
   * @see robot.dSL.impl.DSLPackageImpl#getColorEnum()
   * @generated
   */
  int COLOR_ENUM = 17;


  /**
   * Returns the meta object for class '{@link robot.dSL.RobotBehavior <em>Robot Behavior</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Robot Behavior</em>'.
   * @see robot.dSL.RobotBehavior
   * @generated
   */
  EClass getRobotBehavior();

  /**
   * Returns the meta object for the containment reference list '{@link robot.dSL.RobotBehavior#getBehaviorlist <em>Behaviorlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Behaviorlist</em>'.
   * @see robot.dSL.RobotBehavior#getBehaviorlist()
   * @see #getRobotBehavior()
   * @generated
   */
  EReference getRobotBehavior_Behaviorlist();

  /**
   * Returns the meta object for class '{@link robot.dSL.Behaviors <em>Behaviors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Behaviors</em>'.
   * @see robot.dSL.Behaviors
   * @generated
   */
  EClass getBehaviors();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.Behaviors#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see robot.dSL.Behaviors#getName()
   * @see #getBehaviors()
   * @generated
   */
  EAttribute getBehaviors_Name();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.Behaviors#getSensorExpression <em>Sensor Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sensor Expression</em>'.
   * @see robot.dSL.Behaviors#getSensorExpression()
   * @see #getBehaviors()
   * @generated
   */
  EReference getBehaviors_SensorExpression();

  /**
   * Returns the meta object for the containment reference list '{@link robot.dSL.Behaviors#getActionlist <em>Actionlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actionlist</em>'.
   * @see robot.dSL.Behaviors#getActionlist()
   * @see #getBehaviors()
   * @generated
   */
  EReference getBehaviors_Actionlist();

  /**
   * Returns the meta object for class '{@link robot.dSL.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see robot.dSL.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link robot.dSL.Actions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actions</em>'.
   * @see robot.dSL.Actions
   * @generated
   */
  EClass getActions();

  /**
   * Returns the meta object for class '{@link robot.dSL.LeftMovementAction <em>Left Movement Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Left Movement Action</em>'.
   * @see robot.dSL.LeftMovementAction
   * @generated
   */
  EClass getLeftMovementAction();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.LeftMovementAction#getLeftmove <em>Leftmove</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Leftmove</em>'.
   * @see robot.dSL.LeftMovementAction#getLeftmove()
   * @see #getLeftMovementAction()
   * @generated
   */
  EReference getLeftMovementAction_Leftmove();

  /**
   * Returns the meta object for class '{@link robot.dSL.RightMovementAction <em>Right Movement Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Right Movement Action</em>'.
   * @see robot.dSL.RightMovementAction
   * @generated
   */
  EClass getRightMovementAction();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.RightMovementAction#getRightmove <em>Rightmove</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rightmove</em>'.
   * @see robot.dSL.RightMovementAction#getRightmove()
   * @see #getRightMovementAction()
   * @generated
   */
  EReference getRightMovementAction_Rightmove();

  /**
   * Returns the meta object for class '{@link robot.dSL.RotateMovementAction <em>Rotate Movement Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rotate Movement Action</em>'.
   * @see robot.dSL.RotateMovementAction
   * @generated
   */
  EClass getRotateMovementAction();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.RotateMovementAction#getRotateleft <em>Rotateleft</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rotateleft</em>'.
   * @see robot.dSL.RotateMovementAction#getRotateleft()
   * @see #getRotateMovementAction()
   * @generated
   */
  EAttribute getRotateMovementAction_Rotateleft();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.RotateMovementAction#getLeftdir <em>Leftdir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Leftdir</em>'.
   * @see robot.dSL.RotateMovementAction#getLeftdir()
   * @see #getRotateMovementAction()
   * @generated
   */
  EAttribute getRotateMovementAction_Leftdir();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.RotateMovementAction#getRotateright <em>Rotateright</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rotateright</em>'.
   * @see robot.dSL.RotateMovementAction#getRotateright()
   * @see #getRotateMovementAction()
   * @generated
   */
  EAttribute getRotateMovementAction_Rotateright();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.RotateMovementAction#getRightdir <em>Rightdir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rightdir</em>'.
   * @see robot.dSL.RotateMovementAction#getRightdir()
   * @see #getRotateMovementAction()
   * @generated
   */
  EAttribute getRotateMovementAction_Rightdir();

  /**
   * Returns the meta object for class '{@link robot.dSL.MovementAction <em>Movement Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Movement Action</em>'.
   * @see robot.dSL.MovementAction
   * @generated
   */
  EClass getMovementAction();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.MovementAction#getActionenum <em>Actionenum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Actionenum</em>'.
   * @see robot.dSL.MovementAction#getActionenum()
   * @see #getMovementAction()
   * @generated
   */
  EAttribute getMovementAction_Actionenum();

  /**
   * Returns the meta object for class '{@link robot.dSL.ExpressionBracket <em>Expression Bracket</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression Bracket</em>'.
   * @see robot.dSL.ExpressionBracket
   * @generated
   */
  EClass getExpressionBracket();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ExpressionBracket#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see robot.dSL.ExpressionBracket#getExp()
   * @see #getExpressionBracket()
   * @generated
   */
  EReference getExpressionBracket_Exp();

  /**
   * Returns the meta object for class '{@link robot.dSL.TouchLiteral <em>Touch Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Touch Literal</em>'.
   * @see robot.dSL.TouchLiteral
   * @generated
   */
  EClass getTouchLiteral();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.TouchLiteral#getTouch <em>Touch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Touch</em>'.
   * @see robot.dSL.TouchLiteral#getTouch()
   * @see #getTouchLiteral()
   * @generated
   */
  EAttribute getTouchLiteral_Touch();

  /**
   * Returns the meta object for class '{@link robot.dSL.ColorLiteral <em>Color Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Color Literal</em>'.
   * @see robot.dSL.ColorLiteral
   * @generated
   */
  EClass getColorLiteral();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.ColorLiteral#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see robot.dSL.ColorLiteral#getColor()
   * @see #getColorLiteral()
   * @generated
   */
  EAttribute getColorLiteral_Color();

  /**
   * Returns the meta object for class '{@link robot.dSL.DistanceLiteral <em>Distance Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Distance Literal</em>'.
   * @see robot.dSL.DistanceLiteral
   * @generated
   */
  EClass getDistanceLiteral();

  /**
   * Returns the meta object for the attribute '{@link robot.dSL.DistanceLiteral#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see robot.dSL.DistanceLiteral#getDistance()
   * @see #getDistanceLiteral()
   * @generated
   */
  EAttribute getDistanceLiteral_Distance();

  /**
   * Returns the meta object for class '{@link robot.dSL.ANDexpression <em>AN Dexpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AN Dexpression</em>'.
   * @see robot.dSL.ANDexpression
   * @generated
   */
  EClass getANDexpression();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ANDexpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see robot.dSL.ANDexpression#getLeft()
   * @see #getANDexpression()
   * @generated
   */
  EReference getANDexpression_Left();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ANDexpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see robot.dSL.ANDexpression#getRight()
   * @see #getANDexpression()
   * @generated
   */
  EReference getANDexpression_Right();

  /**
   * Returns the meta object for class '{@link robot.dSL.ORexpression <em>ORexpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ORexpression</em>'.
   * @see robot.dSL.ORexpression
   * @generated
   */
  EClass getORexpression();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ORexpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see robot.dSL.ORexpression#getLeft()
   * @see #getORexpression()
   * @generated
   */
  EReference getORexpression_Left();

  /**
   * Returns the meta object for the containment reference '{@link robot.dSL.ORexpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see robot.dSL.ORexpression#getRight()
   * @see #getORexpression()
   * @generated
   */
  EReference getORexpression_Right();

  /**
   * Returns the meta object for enum '{@link robot.dSL.RotateEnum <em>Rotate Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Rotate Enum</em>'.
   * @see robot.dSL.RotateEnum
   * @generated
   */
  EEnum getRotateEnum();

  /**
   * Returns the meta object for enum '{@link robot.dSL.ActionEnum <em>Action Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Action Enum</em>'.
   * @see robot.dSL.ActionEnum
   * @generated
   */
  EEnum getActionEnum();

  /**
   * Returns the meta object for enum '{@link robot.dSL.TouchEnum <em>Touch Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Touch Enum</em>'.
   * @see robot.dSL.TouchEnum
   * @generated
   */
  EEnum getTouchEnum();

  /**
   * Returns the meta object for enum '{@link robot.dSL.ColorEnum <em>Color Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Color Enum</em>'.
   * @see robot.dSL.ColorEnum
   * @generated
   */
  EEnum getColorEnum();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DSLFactory getDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link robot.dSL.impl.RobotBehaviorImpl <em>Robot Behavior</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.RobotBehaviorImpl
     * @see robot.dSL.impl.DSLPackageImpl#getRobotBehavior()
     * @generated
     */
    EClass ROBOT_BEHAVIOR = eINSTANCE.getRobotBehavior();

    /**
     * The meta object literal for the '<em><b>Behaviorlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT_BEHAVIOR__BEHAVIORLIST = eINSTANCE.getRobotBehavior_Behaviorlist();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.BehaviorsImpl <em>Behaviors</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.BehaviorsImpl
     * @see robot.dSL.impl.DSLPackageImpl#getBehaviors()
     * @generated
     */
    EClass BEHAVIORS = eINSTANCE.getBehaviors();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BEHAVIORS__NAME = eINSTANCE.getBehaviors_Name();

    /**
     * The meta object literal for the '<em><b>Sensor Expression</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIORS__SENSOR_EXPRESSION = eINSTANCE.getBehaviors_SensorExpression();

    /**
     * The meta object literal for the '<em><b>Actionlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BEHAVIORS__ACTIONLIST = eINSTANCE.getBehaviors_Actionlist();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ExpressionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ActionsImpl <em>Actions</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ActionsImpl
     * @see robot.dSL.impl.DSLPackageImpl#getActions()
     * @generated
     */
    EClass ACTIONS = eINSTANCE.getActions();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.LeftMovementActionImpl <em>Left Movement Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.LeftMovementActionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getLeftMovementAction()
     * @generated
     */
    EClass LEFT_MOVEMENT_ACTION = eINSTANCE.getLeftMovementAction();

    /**
     * The meta object literal for the '<em><b>Leftmove</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEFT_MOVEMENT_ACTION__LEFTMOVE = eINSTANCE.getLeftMovementAction_Leftmove();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.RightMovementActionImpl <em>Right Movement Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.RightMovementActionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getRightMovementAction()
     * @generated
     */
    EClass RIGHT_MOVEMENT_ACTION = eINSTANCE.getRightMovementAction();

    /**
     * The meta object literal for the '<em><b>Rightmove</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RIGHT_MOVEMENT_ACTION__RIGHTMOVE = eINSTANCE.getRightMovementAction_Rightmove();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.RotateMovementActionImpl <em>Rotate Movement Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.RotateMovementActionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getRotateMovementAction()
     * @generated
     */
    EClass ROTATE_MOVEMENT_ACTION = eINSTANCE.getRotateMovementAction();

    /**
     * The meta object literal for the '<em><b>Rotateleft</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_MOVEMENT_ACTION__ROTATELEFT = eINSTANCE.getRotateMovementAction_Rotateleft();

    /**
     * The meta object literal for the '<em><b>Leftdir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_MOVEMENT_ACTION__LEFTDIR = eINSTANCE.getRotateMovementAction_Leftdir();

    /**
     * The meta object literal for the '<em><b>Rotateright</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_MOVEMENT_ACTION__ROTATERIGHT = eINSTANCE.getRotateMovementAction_Rotateright();

    /**
     * The meta object literal for the '<em><b>Rightdir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROTATE_MOVEMENT_ACTION__RIGHTDIR = eINSTANCE.getRotateMovementAction_Rightdir();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.MovementActionImpl <em>Movement Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.MovementActionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getMovementAction()
     * @generated
     */
    EClass MOVEMENT_ACTION = eINSTANCE.getMovementAction();

    /**
     * The meta object literal for the '<em><b>Actionenum</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MOVEMENT_ACTION__ACTIONENUM = eINSTANCE.getMovementAction_Actionenum();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ExpressionBracketImpl <em>Expression Bracket</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ExpressionBracketImpl
     * @see robot.dSL.impl.DSLPackageImpl#getExpressionBracket()
     * @generated
     */
    EClass EXPRESSION_BRACKET = eINSTANCE.getExpressionBracket();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION_BRACKET__EXP = eINSTANCE.getExpressionBracket_Exp();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.TouchLiteralImpl <em>Touch Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.TouchLiteralImpl
     * @see robot.dSL.impl.DSLPackageImpl#getTouchLiteral()
     * @generated
     */
    EClass TOUCH_LITERAL = eINSTANCE.getTouchLiteral();

    /**
     * The meta object literal for the '<em><b>Touch</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOUCH_LITERAL__TOUCH = eINSTANCE.getTouchLiteral_Touch();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ColorLiteralImpl <em>Color Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ColorLiteralImpl
     * @see robot.dSL.impl.DSLPackageImpl#getColorLiteral()
     * @generated
     */
    EClass COLOR_LITERAL = eINSTANCE.getColorLiteral();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_LITERAL__COLOR = eINSTANCE.getColorLiteral_Color();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.DistanceLiteralImpl <em>Distance Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.DistanceLiteralImpl
     * @see robot.dSL.impl.DSLPackageImpl#getDistanceLiteral()
     * @generated
     */
    EClass DISTANCE_LITERAL = eINSTANCE.getDistanceLiteral();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DISTANCE_LITERAL__DISTANCE = eINSTANCE.getDistanceLiteral_Distance();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ANDexpressionImpl <em>AN Dexpression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ANDexpressionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getANDexpression()
     * @generated
     */
    EClass AN_DEXPRESSION = eINSTANCE.getANDexpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AN_DEXPRESSION__LEFT = eINSTANCE.getANDexpression_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AN_DEXPRESSION__RIGHT = eINSTANCE.getANDexpression_Right();

    /**
     * The meta object literal for the '{@link robot.dSL.impl.ORexpressionImpl <em>ORexpression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.impl.ORexpressionImpl
     * @see robot.dSL.impl.DSLPackageImpl#getORexpression()
     * @generated
     */
    EClass OREXPRESSION = eINSTANCE.getORexpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OREXPRESSION__LEFT = eINSTANCE.getORexpression_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OREXPRESSION__RIGHT = eINSTANCE.getORexpression_Right();

    /**
     * The meta object literal for the '{@link robot.dSL.RotateEnum <em>Rotate Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.RotateEnum
     * @see robot.dSL.impl.DSLPackageImpl#getRotateEnum()
     * @generated
     */
    EEnum ROTATE_ENUM = eINSTANCE.getRotateEnum();

    /**
     * The meta object literal for the '{@link robot.dSL.ActionEnum <em>Action Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.ActionEnum
     * @see robot.dSL.impl.DSLPackageImpl#getActionEnum()
     * @generated
     */
    EEnum ACTION_ENUM = eINSTANCE.getActionEnum();

    /**
     * The meta object literal for the '{@link robot.dSL.TouchEnum <em>Touch Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.TouchEnum
     * @see robot.dSL.impl.DSLPackageImpl#getTouchEnum()
     * @generated
     */
    EEnum TOUCH_ENUM = eINSTANCE.getTouchEnum();

    /**
     * The meta object literal for the '{@link robot.dSL.ColorEnum <em>Color Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see robot.dSL.ColorEnum
     * @see robot.dSL.impl.DSLPackageImpl#getColorEnum()
     * @generated
     */
    EEnum COLOR_ENUM = eINSTANCE.getColorEnum();

  }

} //DSLPackage
