/**
 * generated by Xtext 2.10.0
 */
package robot.dSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robot Behavior</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.RobotBehavior#getBehaviorlist <em>Behaviorlist</em>}</li>
 * </ul>
 *
 * @see robot.dSL.DSLPackage#getRobotBehavior()
 * @model
 * @generated
 */
public interface RobotBehavior extends EObject
{
  /**
   * Returns the value of the '<em><b>Behaviorlist</b></em>' containment reference list.
   * The list contents are of type {@link robot.dSL.Behaviors}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Behaviorlist</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Behaviorlist</em>' containment reference list.
   * @see robot.dSL.DSLPackage#getRobotBehavior_Behaviorlist()
   * @model containment="true"
   * @generated
   */
  EList<Behaviors> getBehaviorlist();

} // RobotBehavior
