/**
 * generated by Xtext 2.10.0
 */
package robot.dSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import robot.dSL.Behaviors;
import robot.dSL.DSLPackage;
import robot.dSL.RobotBehavior;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Robot Behavior</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link robot.dSL.impl.RobotBehaviorImpl#getBehaviorlist <em>Behaviorlist</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RobotBehaviorImpl extends MinimalEObjectImpl.Container implements RobotBehavior
{
  /**
   * The cached value of the '{@link #getBehaviorlist() <em>Behaviorlist</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBehaviorlist()
   * @generated
   * @ordered
   */
  protected EList<Behaviors> behaviorlist;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RobotBehaviorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DSLPackage.Literals.ROBOT_BEHAVIOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Behaviors> getBehaviorlist()
  {
    if (behaviorlist == null)
    {
      behaviorlist = new EObjectContainmentEList<Behaviors>(Behaviors.class, this, DSLPackage.ROBOT_BEHAVIOR__BEHAVIORLIST);
    }
    return behaviorlist;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DSLPackage.ROBOT_BEHAVIOR__BEHAVIORLIST:
        return ((InternalEList<?>)getBehaviorlist()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DSLPackage.ROBOT_BEHAVIOR__BEHAVIORLIST:
        return getBehaviorlist();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DSLPackage.ROBOT_BEHAVIOR__BEHAVIORLIST:
        getBehaviorlist().clear();
        getBehaviorlist().addAll((Collection<? extends Behaviors>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DSLPackage.ROBOT_BEHAVIOR__BEHAVIORLIST:
        getBehaviorlist().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DSLPackage.ROBOT_BEHAVIOR__BEHAVIORLIST:
        return behaviorlist != null && !behaviorlist.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //RobotBehaviorImpl
