/*
 * generated by Xtext 2.10.0
 */
package robot.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import robot.ide.contentassist.antlr.internal.InternalDSLParser;
import robot.services.DSLGrammarAccess;

public class DSLParser extends AbstractContentAssistParser {

	@Inject
	private DSLGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDSLParser createParser() {
		InternalDSLParser result = new InternalDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getActionsAccess().getAlternatives(), "rule__Actions__Alternatives");
					put(grammarAccess.getExpression3Access().getAlternatives(), "rule__Expression3__Alternatives");
					put(grammarAccess.getRotateEnumAccess().getAlternatives(), "rule__RotateEnum__Alternatives");
					put(grammarAccess.getActionEnumAccess().getAlternatives(), "rule__ActionEnum__Alternatives");
					put(grammarAccess.getTouchEnumAccess().getAlternatives(), "rule__TouchEnum__Alternatives");
					put(grammarAccess.getColorEnumAccess().getAlternatives(), "rule__ColorEnum__Alternatives");
					put(grammarAccess.getBehaviorsAccess().getGroup(), "rule__Behaviors__Group__0");
					put(grammarAccess.getLeftMovementActionAccess().getGroup(), "rule__LeftMovementAction__Group__0");
					put(grammarAccess.getRightMovementActionAccess().getGroup(), "rule__RightMovementAction__Group__0");
					put(grammarAccess.getRotateMovementActionAccess().getGroup(), "rule__RotateMovementAction__Group__0");
					put(grammarAccess.getExpression1Access().getGroup(), "rule__Expression1__Group__0");
					put(grammarAccess.getExpression1Access().getGroup_1(), "rule__Expression1__Group_1__0");
					put(grammarAccess.getExpression2Access().getGroup(), "rule__Expression2__Group__0");
					put(grammarAccess.getExpression2Access().getGroup_1(), "rule__Expression2__Group_1__0");
					put(grammarAccess.getExpressionBracketAccess().getGroup(), "rule__ExpressionBracket__Group__0");
					put(grammarAccess.getTouchLiteralAccess().getGroup(), "rule__TouchLiteral__Group__0");
					put(grammarAccess.getColorLiteralAccess().getGroup(), "rule__ColorLiteral__Group__0");
					put(grammarAccess.getDistanceLiteralAccess().getGroup(), "rule__DistanceLiteral__Group__0");
					put(grammarAccess.getRobotBehaviorAccess().getBehaviorlistAssignment(), "rule__RobotBehavior__BehaviorlistAssignment");
					put(grammarAccess.getBehaviorsAccess().getNameAssignment_1(), "rule__Behaviors__NameAssignment_1");
					put(grammarAccess.getBehaviorsAccess().getSensorExpressionAssignment_3(), "rule__Behaviors__SensorExpressionAssignment_3");
					put(grammarAccess.getBehaviorsAccess().getActionlistAssignment_5(), "rule__Behaviors__ActionlistAssignment_5");
					put(grammarAccess.getLeftMovementActionAccess().getLeftmoveAssignment_1(), "rule__LeftMovementAction__LeftmoveAssignment_1");
					put(grammarAccess.getRightMovementActionAccess().getRightmoveAssignment_1(), "rule__RightMovementAction__RightmoveAssignment_1");
					put(grammarAccess.getRotateMovementActionAccess().getRotateleftAssignment_1(), "rule__RotateMovementAction__RotateleftAssignment_1");
					put(grammarAccess.getRotateMovementActionAccess().getLeftdirAssignment_2(), "rule__RotateMovementAction__LeftdirAssignment_2");
					put(grammarAccess.getRotateMovementActionAccess().getRotaterightAssignment_3(), "rule__RotateMovementAction__RotaterightAssignment_3");
					put(grammarAccess.getRotateMovementActionAccess().getRightdirAssignment_4(), "rule__RotateMovementAction__RightdirAssignment_4");
					put(grammarAccess.getMovementActionAccess().getActionenumAssignment(), "rule__MovementAction__ActionenumAssignment");
					put(grammarAccess.getExpression1Access().getRightAssignment_1_2(), "rule__Expression1__RightAssignment_1_2");
					put(grammarAccess.getExpression2Access().getRightAssignment_1_2(), "rule__Expression2__RightAssignment_1_2");
					put(grammarAccess.getExpressionBracketAccess().getExpAssignment_1(), "rule__ExpressionBracket__ExpAssignment_1");
					put(grammarAccess.getTouchLiteralAccess().getTouchAssignment_1(), "rule__TouchLiteral__TouchAssignment_1");
					put(grammarAccess.getColorLiteralAccess().getColorAssignment_1(), "rule__ColorLiteral__ColorAssignment_1");
					put(grammarAccess.getDistanceLiteralAccess().getDistanceAssignment_1(), "rule__DistanceLiteral__DistanceAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalDSLParser typedParser = (InternalDSLParser) parser;
			typedParser.entryRuleRobotBehavior();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
