/**
 * generated by Xtext 2.10.0
 */
package robot.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;
import robot.tests.DSLInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(DSLInjectorProvider.class)
@SuppressWarnings("all")
public class DSLParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field DSLParsingTest.parseHelper refers to the missing type Model");
  }
}
